### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by rawkode** [picodotdev/alis#83]
Please version this repo, as all my automation on top of this just got destroyed by all the recent changes 

Also, currently none of this repo works due to the many misspellings of PARTITION as PARTITION

Once I get my machine running again, I'll send a PR for the typos

**Comment by picodotdev** [comment]
What automation do you have that relies in alis?

> Also, currently none of this repo works due to the many misspellings of PARTITION as PARTITION

I dont have time to test all possible combinations of configurations, because that as I state in the README I recomend test it first in a VirtualBox machine. maybe it dont works in your specific configuration but that not means that none of this repo works.

By the way, PARTITION misspellings should be fixed already.
